export const ErrorMessages = {
  REPO_URL_REQUIRED: "Se requiere el parámetro repoUrl.",
  FAILED_TO_GET_COMMITS: "Error al obtener commits.",
  REPO_NOT_FOUND: "Repositorio no encontrado",
  BRANCH_NOT_FOUND: "Rama no encontrada",
  DATA_PROCESSING: "Datos aún en procesamiento. Inténtalo de nuevo en unos segundos.",
  FAILED_TO_GET_CONTRIBUTIONS: "Error al obtener contribuciones de usuarios.",
  FAILED_TO_GENERATE_BUBBLE_CHART: "Error al generar datos del diagrama de burbujas.",
 FILE_NOT_FOUND: 'File not found.', 
 REPO_URL_AND_FILE_PATH_REQUIRED: "Se requieren repoUrl y filePath.",
 NOT_ENOUGH_VERSIONS: "No hay suficientes versiones para comparar.",
 FAILED_TO_PERFORM_DEEP_ANALYSIS: "Error al realizar análisis profundo.",
 EXPRESS_ANALYSIS_PARAMS_REQUIRED: "Faltan parámetros requeridos: repoUrl, filePath, commitHashOld y commitHashNew.",
 FAILED_TO_PERFORM_EXPRESS_ANALYSIS: "Error al realizar análisis express.",
 FILE_CONTENT_PARAMS_REQUIRED: "Faltan parámetros: repoUrl, filePath, commitHash.",
 FAILED_TO_GET_FILE_CONTENT: "Error al obtener contenido del archivo.",
 FILE_DIFF_PARAMS_REQUIRED: "Faltan parámetros requeridos.",
 FAILED_TO_GET_FILE_DIFF: "Error al obtener el diff.",
 FIRST_COMMIT_NOT_FOUND: "No se encontró el primer commit del archivo.",
 INTERNAL_ERROR: "Error interno.",
 LATEST_COMMIT_NOT_FOUND: "No se encontró ningún commit para este archivo.",
 FILE_PLAYBACK_PARAMS_REQUIRED: "Faltan parámetros: repoUrl, branch, filePath",
 FAILED_TO_GET_FILE_HISTORY: "Error al obtener historial del archivo.",
 INVALID_INPUT: 'Invalid input provided.',
  BRANCH_NOT_EXISTS_IN_REPO: "La rama no existe en el repositorio.",
  FAILED_TO_GET_REPO_TREE: "Error al obtener el árbol del repositorio.",
  FAILED_TO_GET_CURRENT_BRANCH: "Error al obtener la rama actual.",
 REPO_URL_MISSING: "Falta el parámetro url",
 FAILED_TO_GET_FOLDER_STATS: "Error al obtener estadísticas de carpetas.",
 FAILED_TO_PROCESS_REPO_GRAPH: "Error al procesar el repositorio",
  INTERNAL_SERVER_ERROR: 'Internal server error.', // Consider if 'INTERNAL_ERROR' and 'INTERNAL_SERVER_ERROR' should be the same
  USER_STATS_PARAMS_MISSING: "Parámetros faltantes",
  REPO_URL_REQUIRED_FOR_CSV: "El parámetro repoUrl es obligatorio.",
  REPO_URL_REQUIRED_FOR_BRANCHES: "Se requiere repoUrl",
  COMMIT_NOT_FOUND: "Commit no encontrado",
 USER_NOT_FOUND: 'User not found.',
  SYNC_IN_PROGRESS: 'Repository sync in progress.', 
 SYNC_FAILED: 'Repository sync failed.',
  UNAUTHORIZED: 'Unauthorized access.',
 FORBIDDEN: 'Forbidden access.',
  BAD_REQUEST: 'Bad request.',
 SERVICE_UNAVAILABLE: 'Service unavailable.',
 GATEWAY_TIMEOUT: 'Gateway timeout.',
 CONFLICT: 'Conflict.',
  NOT_IMPLEMENTED: 'Not implemented.',
  
};